services:
  proxy_manager:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '${HTTP_PORT}:80'     # Port HTTP public
      - '${HTTPS_PORT}:443'    # Port HTTPS public
      - '${ADMIN_PORT}:81'     # Port d'administration
    environment:
      DB_POSTGRES_HOST: '${DB_POSTGRES_HOST}'               # Nom d'hôte de la base de données
      DB_POSTGRES_PORT: '${DB_POSTGRES_PORT}'                            # Port de la base de données
      DB_POSTGRES_USER: '${DB_POSTGRES_USER}'                      # Utilisateur de la base de données
      DB_POSTGRES_PASSWORD: '${DB_POSTGRES_PASSWORD}'              # Mot de passe de la base de données
      DB_POSTGRES_NAME: '${DB_POSTGRES_NAME}'                       # Nom de la base de données
    volumes:
      - ${PROXY_DATA_PATH}:/data                                 # Volume pour les données de l'application
      - ${LETSENCRYPT_PATH}:/etc/letsencrypt                    # Volume pour les certificats Let's Encrypt
    depends_on:
      - proxy_manager_db                                           # Dépend de la base de données
    networks:
      - emes                                                      # Réseau utilisé

  proxy_manager_db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: '${DB_POSTGRES_USER}'                        # Utilisateur de la base de données
      POSTGRES_PASSWORD: '${DB_POSTGRES_PASSWORD}'                # Mot de passe de la base de données
      POSTGRES_DB: '${DB_POSTGRES_NAME}'                          # Nom de la base de données
    volumes:
      - ${POSTGRES_DATA_PATH}:/var/lib/postgresql/data            # Volume pour stocker les données de PostgreSQL
    networks: 
      - emes                                                      # Réseau utilisé

networks:
  emes:
    driver: bridge